feat: Реализовать функциональность девятого спринта
KokotAlex/java-filmorate pull request #1
Opened 2022-11-05 14:11 UTC by KokotAlex

2022-11-06 04:42 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-11-06 04:42 UTC, FanaticFiz commented on pom.xml
> +	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
Ну что же, начнем с "многоуважаемого" `pom` файла ))

Для начала немного причесать: очень не хватает отделения друг от друга (пустыми строками) глобальных частей таких как `parent`, `properties`, `dependencies`

Ну и как минимум не хватает указания кодировки в `properties<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`

2022-11-06 04:42 UTC, FanaticFiz commented on pom.xml
> +	<version>0.0.1-SNAPSHOT</version>
Советую прочитать про семантическое версионирование, ну а после не стесняйся - смело проставь версию!

2022-11-06 04:42 UTC, FanaticFiz commented on src/main/resources/application.properties
> +logging.level.ru.yandex.practicum.filmorate=debug
Я буду топить за то чтобы вы сразу привыкали к написанию файла свойств для приложения в формате `yaml -> application.yml`

Соответственно - попрошу тебя этому следовать.Как мини задание: разберись как задать порт для сервиса отличный от дефолтного, и как задать чтобы порт был случайным.(Менять порт на другой не нужно, для тестов нужен именно 8080)

2022-11-06 04:42 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +public class ValidationException extends RuntimeException{
Да, этот ексепшн мы кидаем когда находим ошибку при валидации полей.
Но это у нас веб сервис и это происходит во время запросов к нашему сервису... и клиента мы отсылаем с формулировкой "плохой запрос": BadRequest -> BadRequestException

2022-11-06 04:42 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final Logger log = LoggerFactory.getLogger(FilmController.class);
При описании полей есть правила их порядка. 
Статики описываются первыми.

Кроме этого, между полями(или их группами) с разными модификаторами принято делать отступ в виде пустой строки.

2022-11-06 04:42 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/manager/FilmManager.java
> +public interface FilmManager {
Здорово что решил сделать как и в предыдущих работах, используя свой же опыт и знания!

Давай только тогда вспомним что `FilmManager` и `UserManager` можно было бы привести к одному универсальному интерфейсу.

Первый ша к этому это назвать методы более универсально, не `addFilm()` a `add()`

2022-11-06 04:42 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/manager/FilmManagerInMemory.java
> +            throw new ValidationException("Фильм c id " + filmId + " уже есть в фильмотеке");
Тут должен быть другой ексепшн. Его можно так и назвать: `ConflictException`
По коду ответа который мы будет посылать клиенту, не 400, а 409.

2022-11-06 04:42 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/manager/FilmManagerInMemory.java
> +        final Integer filmId = film.getId();
Фильм новый - у него еще нет id ! 
Новым фильмам мы присваиваем id.

2022-11-06 04:42 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/manager/FilmManagerInMemory.java
> +        final Integer filmId = film.getId();
А вот при обновлении мы условились что фильм приходит с id, тут верно...

2022-11-06 04:42 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/manager/FilmManagerInMemory.java
> +            throw new ValidationException("Фильм c id " + filmId + " отсутствует в фильмотеке");
И тут другой ексепшн... `NotFoundException` и для клиента это будет 404 код ошибки.

2022-11-06 04:42 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/manager/FilmManagerInMemory.java
> +    public List<Film> getFilm() {
Плохо назван метод... 
Название никак не отражает того что возвращается много сущностей.
Такое название подходит для возврата одной записи.

2022-11-06 04:42 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private static final Logger log = LoggerFactory.getLogger(Film.class);
Этот класс просто носитель информации тут не должно быть логера.

2022-11-06 04:42 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        FilmValidator.filmValidate(this);
Это не место для валидации! 
Этим надо заниматься в контроллере.

Но главный мой вопрос, почему ты написал всю валидация вручную?
Я видел у тебя в pom подключенную валидацию, почему не пользуешься аннотациями?

2022-11-06 04:42 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final String name;
У этих моделей, как правило, нет final полей. Это может мешать работе фреймворков в будущем.

2022-11-06 04:42 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/validator/FilmValidator.java
> +            throw new NullPointerException("название фильма не должно быть null");
При валидации бросается только ValidationException. Что бы там с полем ни было...

2022-11-06 04:42 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/validator/FilmValidator.java
> +public class FilmValidator {
По валидации в целом я уже отписался в одном из комментов.

2022-11-06 15:55 UTC, KokotAlex commented on src/main/resources/application.properties
> +logging.level.ru.yandex.practicum.filmorate=debug
Сделал. Чтобы порт был случайным нужно указать значение порта "0".
server.port = 0

2022-11-06 18:03 UTC, KokotAlex commented on pom.xml
> +	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
Исправлено

2022-11-06 18:03 UTC, KokotAlex commented on pom.xml
> +	<version>0.0.1-SNAPSHOT</version>
Исправлено

2022-11-06 18:06 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private static final Logger log = LoggerFactory.getLogger(Film.class);
Исправлено

2022-11-06 18:08 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final String name;
Исправлено

2022-11-06 18:27 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final Logger log = LoggerFactory.getLogger(FilmController.class);
Исправлено

2022-11-07 07:48 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/manager/FilmManager.java
> +public interface FilmManager {
Доработал

2022-11-07 07:55 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/manager/FilmManagerInMemory.java
> +        final Integer filmId = film.getId();
Исправлено

2022-11-07 07:57 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/manager/FilmManagerInMemory.java
> +            throw new ValidationException("Фильм c id " + filmId + " уже есть в фильмотеке");
Код проверки на наличие фильма здесь не нужен вообще т.к. метод всегда должен генерировать новый ID и добавлять фильм. Исправлено

2022-11-07 08:01 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/manager/FilmManagerInMemory.java
> +    public List<Film> getFilm() {
Для классов FilmManagerInMemory и UserManagerInMemory реализован общий абстрактный класс родитель. По этому имена методов стали более общими. Текущий метод стал называться просто "get". Считаю, что данное замечание больше не актуально

2022-11-07 17:57 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +public class ValidationException extends RuntimeException{
Исправлено

2022-11-07 17:58 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/manager/FilmManagerInMemory.java
> +            throw new ValidationException("Фильм c id " + filmId + " отсутствует в фильмотеке");
Исправлено

2022-11-07 17:58 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/validator/FilmValidator.java
> +            throw new NullPointerException("название фильма не должно быть null");
Исправлено

2022-11-07 17:58 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/validator/FilmValidator.java
> +public class FilmValidator {
Валидацию переделал

2022-11-07 18:09 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        FilmValidator.filmValidate(this);
1. Перенес валидацию в контроллер
2. Валидацию написал вручную т.к. не мог добиться того чтобы она заработала с помощью аннотаций. Оказалось я забыл в контроллере в методах прописать "@Valid".

2022-11-07 18:09 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        FilmValidator.filmValidate(this);
Исправлено

2022-11-07 18:48 UTC, FanaticFiz approved these changes

2022-11-07 18:48 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public ResponseEntity<Film> add(@Valid  @RequestBody Film film) {
ResponseEntity вы еще не изучали...
Но хорошо что он тут! )

2022-11-07 18:48 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/manager/ModelManagerAbs.java
> +public abstract class ModelManagerAbs<T> {
А почему ты всё делаешь на абстрактных классах?
А не на интерфейсах?
Вроде предыдущие работы должны были вам именно на интерфейсы натаскать...

2022-11-07 18:48 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/validator/FilmValidator.java
> +            throw new ValidationException("Фильм не мог быть выпущен не раньше 28 декабря 1895.");
Да, этот ексепшн мы кидаем когда находим ошибку при валидации полей.
Но это у нас веб сервис и это происходит во время запросов к нашему сервису... и клиента мы отсылаем с формулировкой "плохой запрос": BadRequest -> BadRequestException

2022-11-14 16:45 UTC, merged