feat: Реализовать функциональность спринта №10
KokotAlex/java-filmorate pull request #2
Opened 2022-11-17 15:57 UTC by KokotAlex

2022-11-17 17:48 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-11-17 17:48 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    @ExceptionHandler(IncorrectParameterException.class)
И ValidationException и IncorrectParameterException это `BadRequestException`
Потому что у нас веб приложение и отвечаем клиенту мы именно как HTTP 404 и в случае не прохода по валидации и в случае неверного параметра, что очень похоже согласись...

2022-11-17 17:48 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +                .status(HttpStatus.INTERNAL_SERVER_ERROR)
А чтобы кидать INTERNAL_SERVER_ERROR 
мы ловим `Throwable e`

2022-11-17 17:48 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +                .body(new ApiError("Incorrect parameter", exception.getMessage()));
И кстати сюда неплохо было бы насыпать логов!

`log.info("500 {}", e.getMessage(), e);`

2022-11-17 17:48 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return ResponseEntity.ok(service.getAll());
Не "прячь" вызовы сервиса, в одну строку с остальным...
Ведь это самое важное что происходит тут, оно достойно отдельной строки, всё остальное второстепенно.

2022-11-17 17:48 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    Optional<Film> update(Film film);
Ты перепутал... метод обновления нет смысла делать Optional, а вот `getById` есть!
Мы запрашиваем сущность и она либо есть и вернётся либо её нет и мы получим пустой Optional.

А с обновлением: мы либо обновим сущность либо упадем с ексепшеном и все...

2022-11-17 17:48 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/servise/FilmService.java
> +        if (filmOptional.isEmpty()) {
При использовании Optional пользуйся методом `orElseThrow`

2022-11-18 06:27 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    @ExceptionHandler(IncorrectParameterException.class)
Исправил

2022-11-18 06:27 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +                .status(HttpStatus.INTERNAL_SERVER_ERROR)
Исправил

2022-11-18 06:41 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +                .body(new ApiError("Incorrect parameter", exception.getMessage()));
Добавил

2022-11-18 07:06 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return ResponseEntity.ok(service.getAll());
Исправил

2022-11-18 09:15 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/servise/FilmService.java
> +        if (filmOptional.isEmpty()) {
Да, метод хороший. Правда я его пока не использую т.к. на сколько я понимаю его не получится использовать если мне нужно вызвать исключение не с конструктором по умолчанию, а передать при создании текст в параметр message

2022-11-18 09:16 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    Optional<Film> update(Film film);
Переделал

2022-11-19 06:56 UTC, FanaticFiz approved these changes

2022-11-19 06:56 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return ResponseEntity.ok(films);
Делай отступ перед `return` это визуально отделит его от основного кода.
Удобно когда точка выхода из метода заметнее.

2022-11-19 06:56 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/servise/FilmService.java
> +    public Film getById(Integer id) {
Вот так это используется, вот так это может выглядеть

```
    @Override
    public Film getById(Integer id) {
        log.debug("Начало получения фильма по id: {}", id);
        return filmStorage.getById(id)
                               .orElseThrow(() -> new NotFoundException("film с id:" + id + " не найден."));
    }
```

2022-11-19 06:56 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/servise/FilmService.java
> +        if (!userStorage.isUserExist(userId)) {
Если ты создал метод и он всё время используется с отрицанием в коде, то просто инвертируй его:

`if (userNotExist(userId))`

Так код будет читаться и восприниматься легче

2022-11-19 06:56 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +    User add(User user);
Заметь что интерфейсы пересекаются по некоторым методам...
Может выделить универсальную часть?

2022-11-19 17:10 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return ResponseEntity.ok(films);
Спасибо! Доработал код.

2022-11-19 17:19 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/servise/FilmService.java
> +    public Film getById(Integer id) {
Отлично! Добавил себе в заметки)

2022-11-19 17:27 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/servise/FilmService.java
> +        if (!userStorage.isUserExist(userId)) {
хороший совет. Подправил

2022-11-19 19:27 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +    User add(User user);
Добавил интерфейс Storage, от которого наследуются другие интерфейсы

2022-11-25 13:32 UTC, merged