feat: Реализовать функциональность спринта №11
KokotAlex/java-filmorate pull request #3
Opened 2022-12-14 11:51 UTC by KokotAlex

2022-12-14 18:51 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-12-14 18:51 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private Map <Integer, TreeSet<Genre>> createFilmsGenreFromRowSet(SqlRowSet genreRows) {
Как то сложно выглядит, но кажется ты избежал таки множественных запросов. Принимается

2022-12-14 18:51 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public Film addLike(Integer filmId, Integer userId) {
Не нужно поддерживать InMemroy реализации... обычно их уже удаляют.

Ну а вообще каждое новое/осмысленное действие в цепочке начинаем с новой строки... т.е. метод orElseThrow должен быть перенесён.

2022-12-14 18:51 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +            genres.add(new Genre(GenreRows.getInt("GENRE_ID"),
Создание жанра можно было бы унести в метод.
Тут конечно мало что выиграется... но в других местах ты тоже так делаешь?
Ну да вот создание Mpa тоже бы вынести в метод...

2022-12-14 18:51 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        // Логика такая:
Никакой логики на должно быть в хранилище!
Логика в сервисах!

2022-12-15 06:13 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public Film addLike(Integer filmId, Integer userId) {
Удалил классы InMemory чтобы не поддерживать устаревший код

2022-12-15 17:40 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +            genres.add(new Genre(GenreRows.getInt("GENRE_ID"),
Создал отдельные методы

2022-12-16 07:20 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        // Логика такая:
Перенес логику в сервис.

2022-12-16 19:26 UTC, FanaticFiz approved these changes

2022-12-16 19:26 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/servise/UserService.java
> +    private void validate(User user) {
Это же не валидация!
Это установка имени пользователя по нашим правилам, можно сказать что это бизнес правила нашего приложения!

2022-12-16 19:26 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    public boolean isUser1HaveFriendUser2(Integer userId1, Integer userId2) {
вот это название мне не нравится...`isUser1HaveFriendUser2(Integer userId1, Integer userId2)`

`isUserHaveAFriend(Integer userId, Integer friendId)`

2022-12-16 19:26 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    public boolean isUserNotExist(Integer userId) {
А вот тут правильно назвал метод! 

Используя этот метод в условиях не нужно его инвертировать и код получается читабельным! Молодец!

2022-12-19 17:17 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    public boolean isUser1HaveFriendUser2(Integer userId1, Integer userId2) {
Исправил

2022-12-19 17:26 UTC, KokotAlex commented on src/main/java/ru/yandex/practicum/filmorate/servise/UserService.java
> +    private void validate(User user) {
Исправил.

2022-12-19 17:32 UTC, merged